pipeline {
    agent any
    environment {
        COVERAGE_THRESHOLD = 80
    }
    stages {
        stage('Checkout') {
            steps {
                // Clonar el código de la rama específica
                checkout scm
            }
        }

       
}

